apiVersion: v1
kind: Service
metadata:
  name: learningsteps-api
  namespace: learningsteps
  labels:
    app: learningsteps-api
spec:
  type: LoadBalancer
  selector:
    app: learningsteps-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000